name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build JAR
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar

      - name: Generate application.yml from secret
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > application.yml

      - name: Copy JAR, application.yml, and Dockerfile to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/libs/*.jar,application.yml,Dockerfile"
          target: "/opt/app"

      - name: Deploy Docker container on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/app
            sudo docker stop spring_app || true
            sudo docker rm spring_app || true
            sudo docker build -t my-spring-app .
            sudo docker run -d --name spring_app -p 8080:8080 my-spring-app:latest
            sudo systemctl reload nginx